//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem_HS
    {
        public string idHocSinh { get; set; }
        public string idMonHoc { get; set; }
        public string idHocKy { get; set; }
        public Nullable<double> Diem15 { get; set; }
        public Nullable<double> Diem45 { get; set; }
    
        public virtual H_KY H_KY { get; set; }
        public virtual HSinh HSinh { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
