//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HSinh()
        {
            this.Diem_HS = new HashSet<Diem_HS>();
        }
    
        public string idHocSinh { get; set; }
        public string MaLop { get; set; }
        public string SDT { get; set; }
        public string HoVaTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayGioSinh { get; set; }
        public string DiaChi { get; set; }
        public string STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem_HS> Diem_HS { get; set; }
    }
}
