//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public string IdLop { get; set; }
        public string IdGVCN { get; set; }
        public string TenLop { get; set; }
        public Nullable<int> SiSo { get; set; }
        public string Khoi { get; set; }
    }
}
